ALPHA: Next Release
SpikeeLabs/novu-python pull request #2
Opened 2023-02-09 12:55 UTC by ryshu

Roadmap:

1 ) Setup the API wrapper:

- [x] events
- [x] subscribers
- [x] topics
- [x] integrations
- [x] layouts
- [ ] notification templates
- [ ] notification groups
- [ ] changes
- [ ] environments
- [ ] feeds
- [ ] messages
- [ ] executions details
- [ ] inbound-parse
- [ ] notifications

2023-02-09 15:04 UTC, Kl0ven approved these changes
lgtm

2023-02-09 15:08 UTC, nils-van-zuijlen requested changes

2023-02-09 18:30 UTC, ryshu commented on .github/workflows/tests.yml
> +          poetry run coverage report -m
Cette partie est pour vérifier la contrainte 100% dans la CI/CD sur chaque version de python

2023-02-09 18:31 UTC, ryshu commented on .github/workflows/coverage.yml
> +          poetry run coverage xml
Non, mais sur codecov oui.

L'objectif de ce job c'est de publier le rapport de couverture (étape suivant) directement sur https://app.codecov.io/gh/SpikeeLabs/novu-python/tree/alpha

2023-02-09 18:33 UTC, ryshu commented on novu/dto/event.py
> +    """Transaction id for trigger."""
Vue ensemble, je préfère conserver partout ça pour l'instant car ça reprend la même logique que les docstrings de la class et ça vient compléter la définition plutôt que la devancer

2023-02-09 18:35 UTC, ryshu commented on novu/enums/provider.py
> +"""Type to define the notion of provider ID, which is one of sms, push, chat, email, or in_app provider ID."""
Non, ça implique juste que c'est une des valeurs des sous-enums. Il me paraît plus précis que l'utilisateur utilise directement l'enum ChatProviderIdEnum dans le cas dont tu parles

2023-02-10 08:31 UTC, ryshu commented on novu/dto/base.py
> +    def from_camel_case(cls: Type[_T], data: dict) -> _T:
Pas compris cette partie

2023-02-18 11:02 UTC, ryshu commented on README.md
> +poetry add novu
Will be handled after the first release with an issue on their repository

2023-02-19 11:12 UTC, ryshu commented on README.md
> +poetry add novu
See in https://github.com/novuhq/novu/issues/2835

2023-03-01 15:35 UTC, nils-van-zuijlen requested changes

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/api/subscriber.py
> +        return PaginatedSubscriberDto.from_camel_case(self.handle_request("GET", self._subscriber_url, payload=payload))
Pareil, ça me semble bizarre de devoir spécifier la page dans la méthode de liste.

Par contre ajouter les méthodes pour l'indexation/slice qui ne chargent que les pages/objets concernés, c'est intéressant.

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/api/topic.py
> +        return PaginatedTopicDto.from_camel_case(self.handle_request("GET", f"{self._topic_url}", payload=payload))
```suggestion
        return PaginatedTopicDto.from_camel_case(self.handle_request("GET", self._topic_url, payload=payload))
```
C'est déjà un `str`, non?

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/api/topic.py
> +        return PaginatedTopicDto.from_camel_case(self.handle_request("GET", f"{self._topic_url}", payload=payload))
Présent à d'autres endroits aussi

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/dto/base.py
> +        'deviceType'
Est-ce qu'il y a une CI de doctest?

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/dto/base.py
> +        ..     )
```suggestion
        >>> @dataclasses.dataclass
        ... class SubscriberPreferenceDto(CamelCaseDto["SubscriberPreferenceDto"]):
        ...     template: DtoDescriptor[SubscriberPreferenceTemplateDto] = (
        ...         DtoDescriptor[SubscriberPreferenceTemplateDto](item_cls=SubscriberPreferenceTemplateDto)
        ...     )
```

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/dto/base.py
> +        ..     )
```suggestion
        >>> @dataclasses.dataclass
        ... class PaginatedTopicDto(CamelCaseDto["PaginatedTopicDto"]):
        ...     data: DtoIterableDescriptor[TopicDto] = DtoIterableDescriptor[TopicDto](
        ...         default_factory=list, item_cls=TopicDto
        ...     )
```

2023-03-01 15:35 UTC, nils-van-zuijlen commented on novu/helpers.py
> +        ...    pass
```suggestion
        >>> from novu.helpers import Singleton
        >>> class MySingleton(metaclass=Singleton)
        ...    pass
```

2023-03-01 15:35 UTC, nils-van-zuijlen commented on pyproject.toml
> +sentry-sdk = "^1.14.0"
Donc sentry est requis pour toutes les installs?

2023-03-01 15:35 UTC, nils-van-zuijlen commented on tests/factories.py
> +    def __init__(self, status, data=None, headers=None, raise_on_call=False):
```suggestion
    def __init__(self, status, data=None, headers=None, raise_on_json_decode=False):
```

2023-03-01 15:35 UTC, nils-van-zuijlen commented on docs/conf.py
> +}
```suggestion
intersphinx_mapping = {
    "python": ("https://docs.python.org/dev/", None),
    "sphinx": ("https://www.sphinx-doc.org/en/stable/", None),
    "requests": ("https://requests.readthedocs.io/en/latest/", None),
}
```

2023-03-01 20:42 UTC, ryshu commented on novu/api/notification_template.py
> +        )
En issue https://github.com/SpikeeLabs/novu-python/issues/14

2023-03-01 20:42 UTC, ryshu commented on novu/api/subscriber.py
> +        return PaginatedSubscriberDto.from_camel_case(self.handle_request("GET", self._subscriber_url, payload=payload))
En issue https://github.com/SpikeeLabs/novu-python/issues/14

2023-03-01 20:50 UTC, ryshu commented on novu/dto/base.py
> +        'deviceType'
Hum, il y a ça je crois mais pas vraiment "utile" pour l'instant je pense

https://pypi.org/project/doctestall/

2023-03-02 07:47 UTC, Kl0ven commented on .github/workflows/semver_build_publish.yaml
> +      - name: Publish distribution 📦 to PyPI
Update the pypi readme ?

2023-03-02 07:47 UTC, Kl0ven commented on novu/api/__init__.py
> +In this SDK, we choose to split the Novu API by business resource to simplify its complexity.
To make it easier to understand.

2023-03-02 09:02 UTC, nils-van-zuijlen approved these changes

2023-03-02 13:05 UTC, merged